var featuresCollection={
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "id":"2",
            "title":"Cartographie de l'essence odonymique de Parc-Extension",
            "media":"Carte",
            "date":"01\/09\/2016",
            "description":"<p>Cartographie de l'essence odonymique de Parc-Extension<\/p><p><img class=\"alignnone  wp-image-698\" src=\"http:\/\/staging-lrsm.anagraph.io\/app\/uploads\/2017\/11\/Cartographie-pour-LRSM-300x188.jpg\" alt=\"\" data-mce-src=\"http:\/\/staging-lrsm.anagraph.io\/app\/uploads\/2017\/11\/Cartographie-pour-LRSM-300x188.jpg\" width=\"934\" height=\"585\"><\/p>",
            "media_type":"photo",
            "time":"05:00",
            "order":1,
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     -73.64569187164308,
                     45.53488113968546
                  ],
                  [
                     -73.61972808837892,
                     45.53088286832488
                  ],
                  [
                     -73.61861228942873,
                     45.53055217150046
                  ],
                  [
                     -73.61741065979005,
                     45.529710388991774
                  ],
                  [
                     -73.61788272857667,
                     45.52913917225734
                  ],
                  [
                     -73.62326860427858,
                     45.5234722877022
                  ],
                  [
                     -73.64687204360963,
                     45.53031216443488
                  ],
                  [
                     -73.64760160446168,
                     45.53177022840588
                  ],
                  [
                     -73.64708662033082,
                     45.53295769587644
                  ],
                  [
                     -73.64569187164308,
                     45.53488113968546
                  ]
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "main":true,
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.6256504058838,
               45.52793659129056
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":"4",
            "title":"Rue Saint-Roch",
            "media":"rue saint-roch",
            "date":"01\/09\/2017",
            "description":"<p>Rue Saint-Roch<br><\/p>",
            "order":2,
            "media_type":"pdf",
            "time":"05:00",
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"LineString",
            "coordinates":[
               [
                  -73.62805366516115,
                  45.53195060459716
               ],
               [
                  -73.63168001174928,
                  45.52580244877406
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":"5",
            "title":"Rue de Li\u00e8ge",
            "media":"PDF-DESSIN",
            "date":"01\/09\/2016",
            "description":"<p>Rue de Li\u00e8ge<br><\/p>",
            "media_type":"pdf",
            "time":"05:00",
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"LineString",
            "coordinates":[
               [
                  -73.64129304885866,
                  45.53419023030068
               ],
               [
                  -73.64408254623415,
                  45.529470378104804
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":"6",
            "title":"Rue Jarry",
            "media":"jarry",
            "date":"01\/09\/2016",
            "description":"<p>Rue Jarry<br><\/p>",
            "media_type":"pdf",
            "time":"05:00",
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"LineString",
            "coordinates":[
               [
                  -73.63459825515748,
                  45.53316813030506
               ],
               [
                  -73.63794565200807,
                  45.52760637833394
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":"7",
            "title":"Rue Hutchison",
            "media":"hutchison",
            "date":"01\/09\/2016",
            "description":"<p>Rue Hutchison<br><\/p>",
            "media_type":"pdf",
            "time":"05:00",
            "story":{
               "id":697,
               "author":null,
               "authors":[
                  {
                     "id":660,
                     "label":"Marion Lessard"
                  }
               ],
               "collaborators":[

               ],
               "text":"",
               "date_type":"range",
               "date_min":"15\/08\/2016",
               "date_max":"04\/09\/2017 00:00",
               "main_tag":{
                  "id":85,
                  "label":"cr\u00e9ation"
               },
               "main_location":{
                  "id":193,
                  "label":"Rue"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":190,
                     "label":"dessin"
                  },
                  {
                     "id":191,
                     "label":"\u00e9crit"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":193,
                     "label":"Rue"
                  }
               ],
               "projects":[
                  {
                     "id":192,
                     "label":"R\u00e9sidence LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"LineString",
            "coordinates":[
               [
                  -73.62456679344179,
                  45.53021470812022
               ],
               [
                  -73.62268924713136,
                  45.52964349650747
               ],
               [
                  -73.62214207649232,
                  45.52964349650747
               ],
               [
                  -73.62025380134584,
                  45.52908731120524
               ],
               [
                  -73.61855864524843,
                  45.528425894497694
               ]
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "main":true,
            "story":{
               "id":666,
               "author":null,
               "authors":[
                  {
                     "id":485,
                     "label":"Cynthia Noury"
                  },
                  {
                     "id":78,
                     "label":"Simon Harel"
                  }
               ],
               "collaborators":[

               ],
               "text":"<p>Par l\u2019exploration du site Outremont qui doit accueillir un \u00ab\u2009campus urbain int\u00e9gr\u00e9\u2009\u00bb d\u00e8s 2019, cette proposition de communication audiovisuelle interrogera le potentiel de refondation de l\u2019Universit\u00e9 de Montr\u00e9al \u00e0 travers ce chantier majeur, ainsi que ses effets symboliques pour la communaut\u00e9 environnante (quatre arrondissements jouxtent en effet le site du futur campus). Ce dernier devant voir le jour \u00e0 l\u2019emplacement d\u2019une ancienne gare de triage, le statut des \u00ab\u2009ruines\u2009\u00bb sera \u00e9galement remis en question, qu\u2019il s\u2019agisse de la d\u00e9signation d\u2019un lieu industriel ruin\u00e9, d\u00e9saffect\u00e9, en voie d\u2019effacement, sans valeur patrimoniale explicite ou encore des entreprises de revalorisation du site (activit\u00e9s \u00e9ph\u00e9m\u00e8res, laboratoires d\u2019innovation sociale). Cette r\u00e9flexion sera d\u00e9velopp\u00e9e par le biais d\u2019un dialogue entre les deux auteurs de la pr\u00e9sentation, soit \u2014 pour reprendre les propos de Readings \u2014 \u00e0 travers l\u2019action de penser ensemble, dans l\u2019aller-retour d\u2019une question pos\u00e9e in situ qui appelle une r\u00e9ponse pour mieux cheminer. \u00c0 partir de vid\u00e9os glan\u00e9es et capt\u00e9es dans les \u00ab\u2009ruines\u2009\u00bb du site Outremont, cet \u00e9change fera ensuite l\u2019objet d\u2019une mise en images d\u2019inspiration ph\u00e9nom\u00e9nologique, ce qui traduira les zones de tension exprim\u00e9es \u00e0 m\u00eame le site. Dans les tableaux visuels ainsi cr\u00e9\u00e9s, les images s\u2019insinueront dans un dialogue qui recourt aux propos des protagonistes et\u00a0aux expressions imaginaires d\u2019un campus toujours immat\u00e9riel, \u00e0 venir.<\/p>\n<p>&nbsp;<\/p>\n<p>Remerciements\u00a0: Erwan Geffroy (LRSM), Madeleine Rh\u00e9aume (Relations avec la communaut\u00e9, site Outremont), Jean-Philippe Drouin (Stantec), Sylvain Lamothe (Stantec).<\/p>\n",
               "media_links":[
                  {
                     "link":"https:\/\/vimeo.com\/231561016",
                     "media_type":"vid\u00e9o"
                  }
               ],
               "date_type":"single",
               "date":"01\/03\/2015",
               "main_tag":{
                  "id":90,
                  "label":"campus MIL"
               },
               "main_location":{
                  "id":77,
                  "label":"Rosemont"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":[
                  {
                     "id":91,
                     "label":"Bill Readings"
                  },
                  {
                     "id":90,
                     "label":"campus MIL"
                  },
                  {
                     "id":180,
                     "label":"campus Outremont"
                  },
                  {
                     "id":84,
                     "label":"colloque"
                  },
                  {
                     "id":85,
                     "label":"cr\u00e9ation"
                  },
                  {
                     "id":79,
                     "label":"espace"
                  },
                  {
                     "id":94,
                     "label":"Gare de triage"
                  },
                  {
                     "id":95,
                     "label":"Imaginaire"
                  },
                  {
                     "id":83,
                     "label":"lieu"
                  },
                  {
                     "id":100,
                     "label":"ph\u00e9nom\u00e9nologie"
                  },
                  {
                     "id":81,
                     "label":"r\u00e9cit"
                  },
                  {
                     "id":101,
                     "label":"ruines"
                  },
                  {
                     "id":8,
                     "label":"Universit\u00e9 de Montr\u00e9al"
                  }
               ],
               "locations":[
                  {
                     "id":124,
                     "label":"campus MIL"
                  },
                  {
                     "id":126,
                     "label":"Mile-Ex"
                  },
                  {
                     "id":128,
                     "label":"Outremont"
                  },
                  {
                     "id":129,
                     "label":"Parc-Extension"
                  },
                  {
                     "id":77,
                     "label":"Rosemont"
                  }
               ],
               "projects":[
                  {
                     "id":106,
                     "label":"ACFAS-Universit\u00e9 en ruines"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.61732482910158,
               45.52568168399758
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "main":true,
            "story":{
               "id":665,
               "author":null,
               "authors":[
                  {
                     "id":654,
                     "label":"Daniel Boisclair"
                  },
                  {
                     "id":495,
                     "label":"Charles de Montambault"
                  }
               ],
               "collaborators":[

               ],
               "text":"<p><em>Les Nouveaux Monuments<\/em> est une \u0153uvre vid\u00e9o explorant l&rsquo;environnement sonore et visuel de l&rsquo;\u00e9changeur Turcot. Visuellement, il s&rsquo;agit d&rsquo;une s\u00e9quence de plans fixes de l&rsquo;architecture autorouti\u00e8re, lesquels comportent des mouvements subtils qui encouragent le spectateur \u00e0 une contempler activement ce paysage singulier et dystopique.<br \/>\nLe design sonore est compos\u00e9 \u00e0 partir d&rsquo;enregistrements pris sur les lieux. Suivant la m\u00eame logique que l&rsquo;encha\u00eenement des images, sa progression offre une exacerbation de l&rsquo;exp\u00e9rience sensible r\u00e9elle du lieu.<\/p>\n<p>&nbsp;<\/p>\n<p>Remerciements : Simon Harel, Marie-\u00c8ve Bradette, Duane Boisclair, LRSM<\/p>\n",
               "date_type":"single",
               "date":"01\/01\/2017",
               "main_tag":{
                  "id":179,
                  "label":"\u00c9changeur Turcot"
               },
               "main_location":{
                  "id":131,
                  "label":"Saint-Henri"
               },
               "main_language":{
                  "id":false,
                  "label":null
               },
               "languages":false,
               "genres":[
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":[
                  {
                     "id":183,
                     "label":"Architecture"
                  },
                  {
                     "id":186,
                     "label":"Autoroute"
                  },
                  {
                     "id":182,
                     "label":"Brutalisme"
                  },
                  {
                     "id":179,
                     "label":"\u00c9changeur Turcot"
                  },
                  {
                     "id":185,
                     "label":"Entropie"
                  },
                  {
                     "id":187,
                     "label":"Infrastructure"
                  },
                  {
                     "id":100,
                     "label":"ph\u00e9nom\u00e9nologie"
                  },
                  {
                     "id":184,
                     "label":"Transport"
                  }
               ],
               "locations":[
                  {
                     "id":188,
                     "label":"\u00c9changeur Turcot"
                  },
                  {
                     "id":131,
                     "label":"Saint-Henri"
                  }
               ],
               "projects":[
                  {
                     "id":109,
                     "label":"Cr\u00e9ation LRSM"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.5996437072754,
               45.46781992987467
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":1,
            "title":"sdfsdfsd",
            "media":"test",
            "date":"",
            "description":"test",
            "main":true,
            "order":1,
            "story":{
               "id":530,
               "author":null,
               "authors":[
                  {
                     "id":496,
                     "label":"Rosie Lanoue Deslandes"
                  }
               ],
               "collaborators":[
                  {
                     "id":486,
                     "label":"Erwan Geffroy"
                  }
               ],
               "text":"",
               "media_links":[
                  {
                     "link":"https:\/\/vimeo.com\/231565189",
                     "media_type":"vid\u00e9o"
                  }
               ],
               "date_type":"range",
               "date_min":"01\/03\/2015",
               "date_max":"20\/04\/2015 00:00",
               "main_tag":{
                  "id":86,
                  "label":"s\u00e9minaire"
               },
               "main_location":{
                  "id":125,
                  "label":"Quartier des spectacles"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":171,
                     "label":"animation"
                  },
                  {
                     "id":172,
                     "label":"essai audiovisuel"
                  },
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":125,
                     "label":"Quartier des spectacles"
                  }
               ],
               "projects":[
                  {
                     "id":121,
                     "label":"S\u00e9minaire LRSM -H2015"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.5662877559662,
               45.50780546091399
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":2,
            "title":"test",
            "media":"test",
            "date":"",
            "description":"test",
            "order":2,
            "story":{
               "id":530,
               "author":null,
               "authors":[
                  {
                     "id":496,
                     "label":"Rosie Lanoue Deslandes"
                  }
               ],
               "collaborators":[
                  {
                     "id":486,
                     "label":"Erwan Geffroy"
                  }
               ],
               "text":"",
               "media_links":[
                  {
                     "link":"https:\/\/vimeo.com\/231565189",
                     "media_type":"vid\u00e9o"
                  }
               ],
               "date_type":"range",
               "date_min":"01\/03\/2015",
               "date_max":"20\/04\/2015 00:00",
               "main_tag":{
                  "id":86,
                  "label":"s\u00e9minaire"
               },
               "main_location":{
                  "id":125,
                  "label":"Quartier des spectacles"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":171,
                     "label":"animation"
                  },
                  {
                     "id":172,
                     "label":"essai audiovisuel"
                  },
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":125,
                     "label":"Quartier des spectacles"
                  }
               ],
               "projects":[
                  {
                     "id":121,
                     "label":"S\u00e9minaire LRSM -H2015"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.56833696365358,
               45.5077189935202
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":3,
            "title":"test",
            "media":"test",
            "date":"",
            "description":"test",
            "order":3,
            "story":{
               "id":530,
               "author":null,
               "authors":[
                  {
                     "id":496,
                     "label":"Rosie Lanoue Deslandes"
                  }
               ],
               "collaborators":[
                  {
                     "id":486,
                     "label":"Erwan Geffroy"
                  }
               ],
               "text":"",
               "media_links":[
                  {
                     "link":"https:\/\/vimeo.com\/231565189",
                     "media_type":"vid\u00e9o"
                  }
               ],
               "date_type":"range",
               "date_min":"01\/03\/2015",
               "date_max":"20\/04\/2015 00:00",
               "main_tag":{
                  "id":86,
                  "label":"s\u00e9minaire"
               },
               "main_location":{
                  "id":125,
                  "label":"Quartier des spectacles"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":171,
                     "label":"animation"
                  },
                  {
                     "id":172,
                     "label":"essai audiovisuel"
                  },
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":125,
                     "label":"Quartier des spectacles"
                  }
               ],
               "projects":[
                  {
                     "id":121,
                     "label":"S\u00e9minaire LRSM -H2015"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.5662341117859,
               45.50985018818656
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "id":4,
            "title":"test",
            "media":"test",
            "date":"test",
            "description":"",
            "order":4,
            "story":{
               "id":530,
               "author":null,
               "authors":[
                  {
                     "id":496,
                     "label":"Rosie Lanoue Deslandes"
                  }
               ],
               "collaborators":[
                  {
                     "id":486,
                     "label":"Erwan Geffroy"
                  }
               ],
               "text":"",
               "media_links":[
                  {
                     "link":"https:\/\/vimeo.com\/231565189",
                     "media_type":"vid\u00e9o"
                  }
               ],
               "date_type":"range",
               "date_min":"01\/03\/2015",
               "date_max":"20\/04\/2015 00:00",
               "main_tag":{
                  "id":86,
                  "label":"s\u00e9minaire"
               },
               "main_location":{
                  "id":125,
                  "label":"Quartier des spectacles"
               },
               "main_language":{
                  "id":76,
                  "label":"Fran\u00e7ais"
               },
               "languages":false,
               "genres":[
                  {
                     "id":171,
                     "label":"animation"
                  },
                  {
                     "id":172,
                     "label":"essai audiovisuel"
                  },
                  {
                     "id":152,
                     "label":"video"
                  }
               ],
               "tags":false,
               "locations":[
                  {
                     "id":125,
                     "label":"Quartier des spectacles"
                  }
               ],
               "projects":[
                  {
                     "id":121,
                     "label":"S\u00e9minaire LRSM -H2015"
                  }
               ]
            }
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -73.56293499469759,
               45.511812890845995
            ]
         }
      }
   ]
};
