<?php
/**
 * Created by PhpStorm.
 * User: C
 * Date: 2017-11-30
 * Time: 2:54 PM
 */

echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset='utf-8' />';
echo '<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />';
echo '<meta property="og:image" content="http://ia.media-imdb.com/rock.jpg"/>';
echo '<title>Le Laboratoire des Récits du Soi Mobile</title>';
echo '';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet" type="text/css">';
echo '<!-- Latest Bootstrap -->';
echo '<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">';
echo '<!-- Latest mapboxgl -->';
echo '';
echo '<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">';
echo '';
echo '<link rel="stylesheet" href="css/main.css"/>';
echo '<link rel="stylesheet" href="css/corpora.css"/>';
echo '<link rel="stylesheet" href="css/modal_sidebar.css"/>';
echo '<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">';
echo '';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet">';
echo '<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">';
echo '';
echo '';
echo '</head>';
echo '';
echo '';
echo '<body>';
echo '';
echo '';
echo '<!-- sidebar -->';
echo '';
echo '<nav id="sideBar" class="col-sm-3 col-md-2 d-none d-sm-block sidebar">';
echo '';
echo '<div id="navbarbrand">';
echo '<a class="navbar-brand" href="#"><img  id="logo" src="img/4.png"></a>';
echo '</div>';
echo '';
echo '<!-- /. Side Menu -->';
echo '</div>';
echo '</nav>';
echo '<!-- /. sidebar -->';
echo '';
echo '';
echo '<!-- top navbar -->';
echo '<nav id="navbar" class="navbar navbar-expand-md navbar-dark fixed-top sticky">';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '';
echo '<div class="collapse navbar-collapse " id="navbarsExampleDefault">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item active mr-5">';
echo '<a class="nav-link" href="index.html">Cartographies <span class="sr-only">(current)</span></a>';
echo '</li>';
echo '<li class="nav-item mr-5">';
echo '<a class="nav-link" href="projets.html">Ses projets</a>';
echo '</li>';
echo '<li class="nav-item mr-5">';
echo '<a class="nav-link" href="corpus.html">Ses corpus</a>';
echo '</li>';
echo '<li class="nav-item mr-5">';
echo '<a class="nav-link" href="apropos.html">Le LRSM</a>';
echo '';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '';
echo '<nav id="submenu" class="navbar-expand-md sticky">';
echo '<div class="collapse navbar-collapse " id="submenuCollapse">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item active mr-5">';
echo '<a class="nav-link" href="tron.html">En cours <span class="sr-only">(current)</span></a>';
echo '</li>';
echo '<li class="nav-item mr-5">';
echo '<a class="nav-link" href="projets.html">Passés</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '<!-- /. top navbar -->';
echo '';
echo '<main role="main" class="container">';
echo '<div class="row">';
echo '';
echo '<div id="corpora" class="col-sm-12 blog-main pt-2 ml-0 mr-0 pl-0 pr-0 mb-4">';
echo '';
echo '<div class="blog-post">';
echo '<!-- Titre dynamique en fonction du routing (Théorique/Littéraire/Médiatique) -->';
echo '<h2 class="blog-post-title pl-5">Corpus Théorique &rarr;dynamique&larr;</h2>';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<h3 id="corpusTitle" class="pt-5 pl-5">Titre du sous ensemble &rarr;dynamique&larr;</h3>';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<div class="pt-5 pl-5">';
echo '<ol id="corpusList">';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '</ol>';
echo '</div>';
echo '';
echo '';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<h3 id="corpusTitle" class="pt-5 pl-5">Titre du sous ensemble &rarr;dynamique&larr;</h3>';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<div class="pt-5 pl-5">';
echo '<ol id="corpusList">';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '</ol>';
echo '</div>';
echo '';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<h3 id="corpusTitle" class="pt-5 pl-5">Titre du sous ensemble &rarr;dynamique&larr;</h3>';
echo '';
echo '<!-- Titre du sous ensemble dynamique -->';
echo '<div class="pt-5 pl-5">';
echo '<ol id="corpusList">';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '<li> « Décès de César Boutteville » [archive], sur idf-echecs.com&rarr;dynamique&larr; </li>';
echo '<li> Les résultats des championnats de Paris [archive] de 1925 à 1975.&rarr;dynamique&larr; </li>';
echo '</ol>';
echo '</div>';
echo '';
echo '<!-- Pagination dynamique -->';
echo '<nav class="blog-pagination col-sm-12">';
echo '<div class="row">';
echo '<div class="col-sm-10 inline text-left">';
echo '<a id="olderPage" class="btn" href="#"><i class="fa fa-arrow-left"></i></a>';
echo '</div>';
echo '<div class="col-sm-2 inline text-right">';
echo '<a id="newerPage" class="btn justify-content-end" href="#"><i class="fa fa-arrow-right"></i></a>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</div><!-- /.blog-post -->';
echo '';
echo '<ul class="ct-socials">';
echo '<li><a href="/" target="_blank"><i class="fa fa-twitter"></i></a>&rarr;dynamique&larr;</li>';
echo '<li><a href="/" target="_blank"><i class="fa fa-facebook"></i></a>&rarr;dynamique&larr;</li>';
echo '<li><a href="/" target="_blank"><i class="fa fa-linkedin"></i></a>&rarr;dynamique&larr;</li>';
echo '</ul>';
echo '';
echo '</div><!-- /.blog-main -->';
echo '</main><!-- /.container -->';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>