# Patricio Gonzalez Vivo (@patriciogv) - 2016

import:
    - ../geometry/tilt.yaml
    - geometry.yaml

styles:
    terrain-base:
        doc:
            author: 
                name: Patricio Gonzalez Vivo
                twitter: patriciogv
            version: 0.0.1
            tangram-version: 0.0.7
            licence: MIT
        mix: [terrain-geometry, geometry-tilt]
        